[general]
background = "#dce0e8"
border = "#9ca0b0"
horizontal_rule = "#ccd0da"
unread_indicator = "#8839ef"

[text]
primary = "#4c4f69"
secondary = "#6c6f85"
tertiary = "#8839ef"
success = "#40a02b"
error = "#d20f39"

[buttons.primary]
background = "#dce0e8"
background_hover = "#e6e9ef"
background_selected = "#eff1f5"
background_selected_hover = "#e6e9ef"

[buttons.secondary]
background = "#e6e9ef"
background_hover = "#bcc0cc"
background_selected = "#ccd0da"
background_selected_hover = "#bcc0cc"

[buffer]
action = "#fe640b"
background = "#e6e9ef"
background_text_input = "#eff1f5"
background_title_bar = "#eff1f5"
border = "#dce0e8"
border_selected = "#7287fd"
code = "#7287fd"
highlight = "#bcc0cc"
nickname = "#04a5e5"
selection = "#ccd0da"
timestamp = "#5c5f77"
topic = "#8c8fa1"
url = "#1e66f5"

[buffer.server_messages]
default = "#df8e1d"